---
# Settings inherited from _quarto.yml
---

# Academic Figures: Common Pitfalls and Best Practices {.title-slide}

::: {.fragment}
*Things that annoy me - An opinionated guide*
:::

**Jan Stanstrup**

# Introduction {background-color="#2c3e50"}

## Why This Matters

::: {.incremental}
- Figures are often the first (and sometimes only) thing readers look at

- Poor quality figures look unprofessional
- Low resolution images look bad when scaled up (e.g. posters)

- Bad visualizations can be misleading
:::

## What We'll Cover

:::: {.columns}
::: {.column width="50%"}

**Do it right**

1. [Color Gradients](#color-gradients)
2. [Heatmap Scaling](#heatmap-scaling)
3. [File Formats](#which-image-format-for-which-purpose)

:::

::: {.column width="50%"}

**Do it easily**

4. [Text Sizing](#text-and-element-sizing)
5. [Themes & Styling](#default-ggplot2-theme)
6. [Saving Plots](#saving-plots-in-r)
7. [Post-Processing](#post-export-editing)

8. [PowerPoint Import](#powerpoint-import)
9. [Factor Ordering](#factor-ordering)
10. [Interactive Plots](#interactive-plots)

:::
::::



{{< include ../book/topics/01_colors.qmd >}}



{{< include ../book/topics/02_heatmaps.qmd >}}



{{< include ../book/topics/03_formats.qmd >}}



{{< include ../book/topics/04_sizing.qmd >}}



{{< include ../book/topics/05_themes.qmd >}}



{{< include ../book/topics/06_saving.qmd >}}



{{< include ../book/topics/07_editing.qmd >}}



{{< include ../book/topics/08_powerpoint.qmd >}}



{{< include ../book/topics/09_factors.qmd >}}



{{< include ../book/topics/10_interactive.qmd >}}


{{< include ../book/resources.qmd >}}
